/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    AccountDTO,
    AuthRequestDTO,
    CharacterDTO,
    CombatIdDTO,
    CombatResultDTO,
    CreateCharacterDTO,
    ExecuteActionDTO,
    InitPveDTO,
    MonsterDTO,
    RegisterDTO,
    SelectCharacterDTO,
    TokenResponseDTO,
} from "./orval.schemas";

import { api } from "./client";

export const performActionInCombat = (
    id: string,
    executeActionDTO: ExecuteActionDTO,
    signal?: AbortSignal,
) => {
    return api<CombatResultDTO>({
        url: `/combats/${id}/actions/execute`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: executeActionDTO,
        signal,
    });
};

export const getPerformActionInCombatMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof performActionInCombat>>,
        TError,
        { id: string; data: ExecuteActionDTO },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof performActionInCombat>>,
    TError,
    { id: string; data: ExecuteActionDTO },
    TContext
> => {
    const mutationKey = ["performActionInCombat"];
    const { mutation: mutationOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof performActionInCombat>>,
        { id: string; data: ExecuteActionDTO }
    > = (props) => {
        const { id, data } = props ?? {};

        return performActionInCombat(id, data);
    };

    return { mutationFn, ...mutationOptions };
};

export type PerformActionInCombatMutationResult = NonNullable<
    Awaited<ReturnType<typeof performActionInCombat>>
>;
export type PerformActionInCombatMutationBody = ExecuteActionDTO;
export type PerformActionInCombatMutationError = unknown;

export const usePerformActionInCombat = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof performActionInCombat>>,
            TError,
            { id: string; data: ExecuteActionDTO },
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof performActionInCombat>>,
    TError,
    { id: string; data: ExecuteActionDTO },
    TContext
> => {
    const mutationOptions = getPerformActionInCombatMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const initPveCombat = (initPveDTO: InitPveDTO, signal?: AbortSignal) => {
    return api<CombatResultDTO>({
        url: `/combats/init/pve`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: initPveDTO,
        signal,
    });
};

export const getInitPveCombatMutationOptions = <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof initPveCombat>>,
        TError,
        { data: InitPveDTO },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof initPveCombat>>,
    TError,
    { data: InitPveDTO },
    TContext
> => {
    const mutationKey = ["initPveCombat"];
    const { mutation: mutationOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof initPveCombat>>,
        { data: InitPveDTO }
    > = (props) => {
        const { data } = props ?? {};

        return initPveCombat(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type InitPveCombatMutationResult = NonNullable<Awaited<ReturnType<typeof initPveCombat>>>;
export type InitPveCombatMutationBody = InitPveDTO;
export type InitPveCombatMutationError = unknown;

export const useInitPveCombat = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof initPveCombat>>,
            TError,
            { data: InitPveDTO },
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof initPveCombat>>,
    TError,
    { data: InitPveDTO },
    TContext
> => {
    const mutationOptions = getInitPveCombatMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const create = (createCharacterDTO: CreateCharacterDTO, signal?: AbortSignal) => {
    return api<CharacterDTO>({
        url: `/characters`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createCharacterDTO,
        signal,
    });
};

export const getCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof create>>,
        TError,
        { data: CreateCharacterDTO },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: CreateCharacterDTO },
    TContext
> => {
    const mutationKey = ["create"];
    const { mutation: mutationOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof create>>,
        { data: CreateCharacterDTO }
    > = (props) => {
        const { data } = props ?? {};

        return create(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>;
export type CreateMutationBody = CreateCharacterDTO;
export type CreateMutationError = unknown;

export const useCreate = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof create>>,
            TError,
            { data: CreateCharacterDTO },
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: CreateCharacterDTO },
    TContext
> => {
    const mutationOptions = getCreateMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getAllByAccountId = (signal?: AbortSignal) => {
    return api<CharacterDTO[]>({ url: `/characters/selects`, method: "GET", signal });
};

export const getGetAllByAccountIdQueryKey = () => {
    return [`/characters/selects`] as const;
};

export const getGetAllByAccountIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getAllByAccountId>>,
    TError = unknown,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllByAccountId>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAllByAccountIdQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllByAccountId>>> = ({ signal }) =>
        getAllByAccountId(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAllByAccountId>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllByAccountIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAllByAccountId>>
>;
export type GetAllByAccountIdQueryError = unknown;

export function useGetAllByAccountId<
    TData = Awaited<ReturnType<typeof getAllByAccountId>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAllByAccountId>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAllByAccountId>>,
                    TError,
                    Awaited<ReturnType<typeof getAllByAccountId>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllByAccountId<
    TData = Awaited<ReturnType<typeof getAllByAccountId>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAllByAccountId>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAllByAccountId>>,
                    TError,
                    Awaited<ReturnType<typeof getAllByAccountId>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllByAccountId<
    TData = Awaited<ReturnType<typeof getAllByAccountId>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAllByAccountId>>, TError, TData>
        >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetAllByAccountId<
    TData = Awaited<ReturnType<typeof getAllByAccountId>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAllByAccountId>>, TError, TData>
        >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetAllByAccountIdQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const selectCharacter = (selectCharacterDTO: SelectCharacterDTO, signal?: AbortSignal) => {
    return api<CharacterDTO>({
        url: `/characters/selects`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: selectCharacterDTO,
        signal,
    });
};

export const getSelectCharacterMutationOptions = <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof selectCharacter>>,
        TError,
        { data: SelectCharacterDTO },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof selectCharacter>>,
    TError,
    { data: SelectCharacterDTO },
    TContext
> => {
    const mutationKey = ["selectCharacter"];
    const { mutation: mutationOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof selectCharacter>>,
        { data: SelectCharacterDTO }
    > = (props) => {
        const { data } = props ?? {};

        return selectCharacter(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type SelectCharacterMutationResult = NonNullable<
    Awaited<ReturnType<typeof selectCharacter>>
>;
export type SelectCharacterMutationBody = SelectCharacterDTO;
export type SelectCharacterMutationError = unknown;

export const useSelectCharacter = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof selectCharacter>>,
            TError,
            { data: SelectCharacterDTO },
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof selectCharacter>>,
    TError,
    { data: SelectCharacterDTO },
    TContext
> => {
    const mutationOptions = getSelectCharacterMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const removeSelectedCharacter = () => {
    return api<void>({ url: `/characters/selects`, method: "DELETE" });
};

export const getRemoveSelectedCharacterMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof removeSelectedCharacter>>,
        TError,
        void,
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof removeSelectedCharacter>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["removeSelectedCharacter"];
    const { mutation: mutationOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof removeSelectedCharacter>>,
        void
    > = () => {
        return removeSelectedCharacter();
    };

    return { mutationFn, ...mutationOptions };
};

export type RemoveSelectedCharacterMutationResult = NonNullable<
    Awaited<ReturnType<typeof removeSelectedCharacter>>
>;

export type RemoveSelectedCharacterMutationError = unknown;

export const useRemoveSelectedCharacter = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof removeSelectedCharacter>>,
            TError,
            void,
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof removeSelectedCharacter>>,
    TError,
    void,
    TContext
> => {
    const mutationOptions = getRemoveSelectedCharacterMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const login = (authRequestDTO: AuthRequestDTO, signal?: AbortSignal) => {
    return api<TokenResponseDTO>({
        url: `/authenticate`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: authRequestDTO,
        signal,
    });
};

export const getLoginMutationOptions = <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof login>>,
        TError,
        { data: AuthRequestDTO },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: AuthRequestDTO },
    TContext
> => {
    const mutationKey = ["login"];
    const { mutation: mutationOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof login>>,
        { data: AuthRequestDTO }
    > = (props) => {
        const { data } = props ?? {};

        return login(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type LoginMutationBody = AuthRequestDTO;
export type LoginMutationError = unknown;

export const useLogin = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof login>>,
            TError,
            { data: AuthRequestDTO },
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: AuthRequestDTO },
    TContext
> => {
    const mutationOptions = getLoginMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const registerRequest = (registerDTO: RegisterDTO, signal?: AbortSignal) => {
    return api<AccountDTO>({
        url: `/accounts/register`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: registerDTO,
        signal,
    });
};

export const getRegisterRequestMutationOptions = <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof registerRequest>>,
        TError,
        { data: RegisterDTO },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof registerRequest>>,
    TError,
    { data: RegisterDTO },
    TContext
> => {
    const mutationKey = ["registerRequest"];
    const { mutation: mutationOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof registerRequest>>,
        { data: RegisterDTO }
    > = (props) => {
        const { data } = props ?? {};

        return registerRequest(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type RegisterRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof registerRequest>>
>;
export type RegisterRequestMutationBody = RegisterDTO;
export type RegisterRequestMutationError = unknown;

export const useRegisterRequest = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof registerRequest>>,
            TError,
            { data: RegisterDTO },
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof registerRequest>>,
    TError,
    { data: RegisterDTO },
    TContext
> => {
    const mutationOptions = getRegisterRequestMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getMonsterById = (id: string, signal?: AbortSignal) => {
    return api<MonsterDTO>({ url: `/monsters/${id}`, method: "GET", signal });
};

export const getGetMonsterByIdQueryKey = (id?: string) => {
    return [`/monsters/${id}`] as const;
};

export const getGetMonsterByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getMonsterById>>,
    TError = unknown,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonsterById>>, TError, TData>>;
    },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetMonsterByIdQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMonsterById>>> = ({ signal }) =>
        getMonsterById(id, signal);

    return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getMonsterById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMonsterByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMonsterById>>>;
export type GetMonsterByIdQueryError = unknown;

export function useGetMonsterById<
    TData = Awaited<ReturnType<typeof getMonsterById>>,
    TError = unknown,
>(
    id: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonsterById>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getMonsterById>>,
                    TError,
                    Awaited<ReturnType<typeof getMonsterById>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMonsterById<
    TData = Awaited<ReturnType<typeof getMonsterById>>,
    TError = unknown,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getMonsterById>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getMonsterById>>,
                    TError,
                    Awaited<ReturnType<typeof getMonsterById>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMonsterById<
    TData = Awaited<ReturnType<typeof getMonsterById>>,
    TError = unknown,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonsterById>>, TError, TData>>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMonsterById<
    TData = Awaited<ReturnType<typeof getMonsterById>>,
    TError = unknown,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonsterById>>, TError, TData>>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetMonsterByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getCombatById = (id: string, signal?: AbortSignal) => {
    return api<CombatResultDTO>({ url: `/combats/${id}`, method: "GET", signal });
};

export const getGetCombatByIdQueryKey = (id?: string) => {
    return [`/combats/${id}`] as const;
};

export const getGetCombatByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getCombatById>>,
    TError = unknown,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCombatById>>, TError, TData>>;
    },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCombatByIdQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCombatById>>> = ({ signal }) =>
        getCombatById(id, signal);

    return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getCombatById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCombatByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCombatById>>>;
export type GetCombatByIdQueryError = unknown;

export function useGetCombatById<
    TData = Awaited<ReturnType<typeof getCombatById>>,
    TError = unknown,
>(
    id: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCombatById>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCombatById>>,
                    TError,
                    Awaited<ReturnType<typeof getCombatById>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCombatById<
    TData = Awaited<ReturnType<typeof getCombatById>>,
    TError = unknown,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCombatById>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCombatById>>,
                    TError,
                    Awaited<ReturnType<typeof getCombatById>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCombatById<
    TData = Awaited<ReturnType<typeof getCombatById>>,
    TError = unknown,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCombatById>>, TError, TData>>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetCombatById<
    TData = Awaited<ReturnType<typeof getCombatById>>,
    TError = unknown,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCombatById>>, TError, TData>>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetCombatByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getActiveCombatByParticipantId = (signal?: AbortSignal) => {
    return api<CombatIdDTO>({ url: `/combats/active`, method: "GET", signal });
};

export const getGetActiveCombatByParticipantIdQueryKey = () => {
    return [`/combats/active`] as const;
};

export const getGetActiveCombatByParticipantIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getActiveCombatByParticipantId>>, TError, TData>
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetActiveCombatByParticipantIdQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveCombatByParticipantId>>> = ({
        signal,
    }) => getActiveCombatByParticipantId(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetActiveCombatByParticipantIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getActiveCombatByParticipantId>>
>;
export type GetActiveCombatByParticipantIdQueryError = unknown;

export function useGetActiveCombatByParticipantId<
    TData = Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
                    TError,
                    Awaited<ReturnType<typeof getActiveCombatByParticipantId>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetActiveCombatByParticipantId<
    TData = Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
                    TError,
                    Awaited<ReturnType<typeof getActiveCombatByParticipantId>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetActiveCombatByParticipantId<
    TData = Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetActiveCombatByParticipantId<
    TData = Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getActiveCombatByParticipantId>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetActiveCombatByParticipantIdQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getSelectedCharacter = (signal?: AbortSignal) => {
    return api<CharacterDTO>({ url: `/characters/selects/me`, method: "GET", signal });
};

export const getGetSelectedCharacterQueryKey = () => {
    return [`/characters/selects/me`] as const;
};

export const getGetSelectedCharacterQueryOptions = <
    TData = Awaited<ReturnType<typeof getSelectedCharacter>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getSelectedCharacter>>, TError, TData>
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetSelectedCharacterQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSelectedCharacter>>> = ({ signal }) =>
        getSelectedCharacter(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getSelectedCharacter>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSelectedCharacterQueryResult = NonNullable<
    Awaited<ReturnType<typeof getSelectedCharacter>>
>;
export type GetSelectedCharacterQueryError = unknown;

export function useGetSelectedCharacter<
    TData = Awaited<ReturnType<typeof getSelectedCharacter>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getSelectedCharacter>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getSelectedCharacter>>,
                    TError,
                    Awaited<ReturnType<typeof getSelectedCharacter>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSelectedCharacter<
    TData = Awaited<ReturnType<typeof getSelectedCharacter>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getSelectedCharacter>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getSelectedCharacter>>,
                    TError,
                    Awaited<ReturnType<typeof getSelectedCharacter>>
                >,
                "initialData"
            >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSelectedCharacter<
    TData = Awaited<ReturnType<typeof getSelectedCharacter>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getSelectedCharacter>>, TError, TData>
        >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSelectedCharacter<
    TData = Awaited<ReturnType<typeof getSelectedCharacter>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getSelectedCharacter>>, TError, TData>
        >;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetSelectedCharacterQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}
