/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface ExecuteActionDTO {
    combatId?: string;
    actionType?: string;
}

export type CombatResultDTOStatus =
    (typeof CombatResultDTOStatus)[keyof typeof CombatResultDTOStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CombatResultDTOStatus = {
    IN_PROGRESS: "IN_PROGRESS",
    FINISHED: "FINISHED",
    CANCELLED: "CANCELLED",
} as const;

export type CombatResultDTOCombatSide =
    (typeof CombatResultDTOCombatSide)[keyof typeof CombatResultDTOCombatSide];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CombatResultDTOCombatSide = {
    ATTACKER: "ATTACKER",
    DEFENDER: "DEFENDER",
} as const;

export interface CombatResultDTO {
    combatId?: string;
    attacker?: ParticipantDTO;
    defender?: ParticipantDTO;
    status?: CombatResultDTOStatus;
    combatSide?: CombatResultDTOCombatSide;
}

export interface ParticipantDTO {
    id?: string;
    currentHp?: number;
    maxHp?: number;
}

export interface InitPveDTO {
    monsterId: string;
}

export interface CreateCharacterDTO {
    /**
     * @minLength 3
     * @maxLength 20
     * @pattern ^[a-zA-Z0-9_-]+$
     */
    characterName: string;
}

export interface CharacterDTO {
    id?: string;
    characterName?: string;
    health?: number;
    intelligence?: number;
}

export interface SelectCharacterDTO {
    characterId?: string;
}

export interface AuthRequestDTO {
    email: string;
    /**
     * @minLength 8
     * @maxLength 2147483647
     */
    password: string;
}

export interface TokenResponseDTO {
    token?: string;
}

export interface RegisterDTO {
    email: string;
    /**
     * @minLength 8
     * @maxLength 32
     */
    password: string;
}

export interface AccountDTO {
    id?: string;
    email?: string;
}

export interface MonsterDTO {
    id?: string;
    name?: string;
    currentHealth?: number;
    maxHealth?: number;
    intelligence?: number;
}

export interface CombatIdDTO {
    combatId?: string;
}
