/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from "zod";

export const performActionInCombatParams = zod.object({
    id: zod.uuid(),
});

export const performActionInCombatBody = zod.object({
    combatId: zod.uuid().optional(),
    actionType: zod.string().optional(),
});

export const initPveCombatBody = zod.object({
    monsterId: zod.uuid(),
});

export const createBodyCharacterNameMin = 3;
export const createBodyCharacterNameMax = 20;
export const createBodyCharacterNameRegExp = new RegExp("^[a-zA-Z0-9_-]+$");

export const createBody = zod.object({
    characterName: zod
        .string()
        .min(createBodyCharacterNameMin)
        .max(createBodyCharacterNameMax)
        .regex(createBodyCharacterNameRegExp),
});

export const selectCharacterBody = zod.object({
    characterId: zod.uuid().optional(),
});

export const loginBodyPasswordMin = 8;
export const loginBodyPasswordMax = 2147483647;

export const loginBody = zod.object({
    email: zod.string(),
    password: zod.string().min(loginBodyPasswordMin).max(loginBodyPasswordMax),
});

export const registerRequestBodyPasswordMin = 8;
export const registerRequestBodyPasswordMax = 32;

export const registerRequestBody = zod.object({
    email: zod.string(),
    password: zod.string().min(registerRequestBodyPasswordMin).max(registerRequestBodyPasswordMax),
});

export const getMonsterByIdParams = zod.object({
    id: zod.uuid(),
});

export const getCombatByIdParams = zod.object({
    id: zod.uuid(),
});
